services:
  web:
    # 현재 폴더(.)를 기준으로 Docker 이미지를 빌드
    build: .
    # 컨테이너 : 호스트
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    # db 서비스가 시작된 후에 실행되도록 의존성을 설정
    depends_on:
      - db

    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123!
      - MYSQL_DATABASE=review_analyzer_db

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    ports:
      - "3307:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ./app/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: konkuk123!
      MYSQL_DATABASE: review_analyzer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123!